/**
 * Generated by `appwrap init`/`sync` from appwrap.json `modules`. Do not edit.
 * Committed DEFAULT = every opt-in capability active (back-compat: matches pre-modules behavior).
 * The CLI overwrites this with the resolved active set for the app being built.
 */
export const ACTIVE_MODULE_NAMES: string[] = [
  'notifications', 'biometrics', 'geo', 'photos', 'camera', 'media',
  'motion', 'contacts', 'calendar', 'reviews', 'billing',
];
