/**
 * Generated by `appwrap init`/`sync`. iOS BGTaskScheduler launch handlers MUST be registered at
 * `applicationDidFinishLaunchingWithOptions` (Apple's rule) — too early for the page-load handler
 * barrel. The AppDelegate calls {@link registerBackgroundLaunchHandlers} from didFinishLaunching; the
 * CLI rewrites this to import the real implementation ONLY when the `backgroundTask` module is active
 * (so a build without it never references BGTaskScheduler). Default = no-op. Do not edit.
 */
export function registerBackgroundLaunchHandlers(): void {}
