/**
 * Generated by `appwrap init`/`sync`. Registers opt-in modules that own their own handler file, so a
 * build that doesn't enable them never imports (or bundles) their native code. Do not edit.
 * Committed DEFAULT registers all optional groups (back-compat). The CLI rewrites the imports/calls
 * to only the active OPTIONAL_GROUPS.
 */
// Default registers no optional modules (health & friends are strictly opt-in via appwrap.json
// `modules`). The CLI rewrites this barrel to import only the active OPTIONAL_GROUPS.
export function registerOptionalHandlers(): void {
}
