/**
 * Generated by `appwrap init`/`sync` from the appwrap config `plugins`. Do not edit.
 * Committed DEFAULT registers NO plugins (parity with the module barrels): a build without `plugins`
 * imports no plugin bundle and compiles no plugin glue. The CLI (`regenerateMobilePlugins`) rewrites
 * this to import each configured plugin's bundle and register its handlers.
 */
export function registerPlugins(): void {
}
